### ISSUE TITLE
Add support for converting syntax files

### ISSUE THREAD

**Issue by OmgImAlexis** [idleberg/atomizr-cli#1]
Would it be possible for you to add support for converting syntax files?

**Comment by idleberg** [comment]
I would love that, but I'm afraid that's a bit over my head. I have created several syntax files for Atom and Sublime Text, but there are parts that I don't understand at all. But you can use `apm` convert TextMate syntax files into Atom.

**Comment by OmgImAlexis** [comment]
What do you mean by "But you can use `apm` convert TextMate syntax files into Atom."?

**Comment by idleberg** [comment]
See http://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/
