### ISSUE TITLE
poor conversion from Atom to TextMate

### ISSUE THREAD

**Issue by gour** [idleberg/atomizr-cli#2]
I'd like to convert Atom's [snippets](https://github.com/GBratsos/atom-zurb-foundation) to TextMate syntax in order to import those into Emacs' yasnippet, but conversion is quite poor - iow. original Atom's `components.cson` file is 48K, but converted `components.tmSnippet` is only bytes containing only:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>content</key>
    <string>&lt;ul class="no-bullets"&gt;
  &lt;li&gt;$0&lt;/li&gt;
&lt;/ul&gt;</string>
    <key>tabTrigger</key>
    <string>no-bullets</string>
    <key>name</key>
    <string>No-Bullet list</string>
    <key>scope</key>
    <string>text.html</string>
    <key>uuid</key>
    <string>c045b4cc-fff3-4777-935d-0ff60f0e8ee8</string>
  </dict>
</plist>
```

Any idea what is the reason behind it?

**Comment by idleberg** [comment]
I don't use TextMate, but as far as I know a `.tmSnippet` file can only contain one snippet. Hence only the first Atom snippet ends up in a TextMate snippet.

**Comment by gour** [comment]
> I don't use TextMate, but as far as I know a .tmSnippet file can only contain one snippet. 

I see...let me say that my plan to convert to `tmSnippet` is in order to be able to convert to Emacs' [yasnippet](https://github.com/joaotavora/yasnippet) eventually. Have you thought about adding support for `yasnippet`?

> Hence only the first Atom snippet ends up in a TextMate snippet.

Any idea how can then one convert to TextMate?

**Comment by idleberg** [comment]
> Have you thought about adding support for `yasnippet`?

I have not, because I don't know it. But since it looks to be quite similar, it should be fairly trivial. Currently I have other projects with higher priority, so I don't know when I can get to it.

> Any idea how can then one convert to TextMate?

I can think of a workaround. Try the following (untested):

```sh
# Prerequisites
$ npm install node-atomizr sublime-tinker-tools

# Convert Atom snippets into Sublime Text completions
$ atomizr atom-snippets.cson --target sublime

# Convert Sublime Text completions into Sublime Text snippets
$ scissors atom-snippets.sublime-completions --output snippets

# Convert Sublime Text snippets into TextMate snippets
$ atomizr "snippets/*.sublime-snippet" --target textmate
```

**Comment by gour** [comment]
> I have not, because I don't know it. But since it looks to be quite similar, it should be fairly trivial. 

That's good to hear.

> Currently I have other projects with higher priority, so I don't know when I can get to it. In general I've been considering a complete rewrite, possibly in TypeScript.

I'd be glad to help, but Javascript & Co. are simply not my cup of coffee. 😞 

> I can think of a workaround. Try the following (untested):

Works very well. Thanks a lot!

Still, having direct support for yasnippet would be great, so I'll submit a ticket as reminder...
